### ISSUE TITLE
Completion does'nt work correctly in CSS Scope

### ISSUE THREAD

**Issue by mschick** [idleberg/sublime-icon-fonts#10]
**Completion only works outside CSS-Classes:**
Example: 
```
.class {  
    fa-star + tab (or even with ctrl + space) leads to nothing...  
}
```
or 
```
.class { 
     content: 'fa-star + tab'; epands to 
  -> content: 'content: '\f005';'; 
}
```
```
.class { ... }
fa-star + tab 
.class2 { ... }

expands to -> 

.class { ... }
 content: '\f005';
.class2 { ... }
```

**Comment by idleberg** [comment]
It's true that these completions should be scoped more strictly. Rather than using `source.css`, it should be `source.css meta.property-list.css` as this screenshot shows:

![screen shot 2017-01-31 at 13 51 49](https://cloud.githubusercontent.com/assets/1504938/22465542/9060889a-e7bc-11e6-99da-480824256e74.png)

However, when I use this scope, the completions don't get triggered at all, so this is –to my understanding– an issue with the CSS package and should be posted [here](https://github.com/sublimehq/Packages/issues).

Once that is resolved, I will change the scope to `source.css meta.property-list.css, source.less, source.scss meta.property-list.scss, source.stylus`. Until then, the only work-around I can think of is using SCSS for CSS files.

**Comment by idleberg** [comment]
I've posted an issue [here](https://github.com/sublimehq/Packages/issues/794). In the meantime I have modified the default scope for all CSS completions in the master.

**Comment by idleberg** [comment]
I have converted all completions into snippets, which should circumvent the issue. In a next step, I will switch to a custom completions format.

**Comment by idleberg** [comment]
@mschick Can we close this issue?

**Comment by mschick** [comment]
Yes. Thank you!

Jan T. Sott <notifications@github.com> schrieb am So., 2. Apr. 2017, 15:29:
