### ISSUE TITLE
System instability

### ISSUE THREAD

**Issue by IanCaunce** [idleberg/sublime-icon-fonts#11]
Since your recent release, my sublime installation has been unstable. When launching sublime, just after it reports in the console that your package has been "reloaded", sublime will freeze. On the odd occasion that it does launch successfully, the length of time it takes has greatly increased.

Disabling your package has returned sublime to a stable state.

I know your recent update brought jsx support which consequently added approximately 10k new snippets. Could it be that sublime is reaching some kind of threshold regarding snippets and crashing?

**Comment by idleberg** [comment]
I would love to convert these snippets into completions, since that would increase maintainability and improve my workflow (I release these snippets for three different editors!) Unfortunately, completions work fuzzy, which oftentimes leads to undesired completions. On the occasion of this issue, I will look into some alternatives (which have been [suggested](https://forum.sublimetext.com/t/when-to-use-snippets-completions/20650/3?u=idleberg) before)

Just out of interest, is Sublime Text (or the packages folder) installed on a „traditional” hard drive?

**Comment by IanCaunce** [comment]
Thanks for the quick response!

Sublime is installed on an SSD.

Incidentally I actually use the same package in atom and it works great!

Could you not split each icon font into its own package? It might make maintenance a lot harder as you would be maintaining several packages but it could potentially issues caused by having too many snippets.

For example, I predominantly use font awesome and I don't have a need for all the others. I can imagine other people being in similar situations where they only need snippets for one or two icon sets.
