### ISSUE TITLE
Snippet from command pallet.

### ISSUE THREAD

**Issue by IanCaunce** [idleberg/sublime-icon-fonts#9]
Previously you could press `Ctrl` + `Shift` + `p` to bring up the command pallet, type something like `fa-plus` and press `enter` to place the snippet into the current tab.

Recently I am unable to do this anymore and I am unsure which release caused it. The snippets still appear in the command pallet but they only display and are searchable by the opening html tag of the snippet.

See screenshot 

![image](https://cloud.githubusercontent.com/assets/10065879/20602510/73c1a7ec-b255-11e6-921b-196d5c425d10.png)

Edit: I believe the issue was caused in this commit ea42f83807d6a79ee406332c365e00f300a47872 when the descriptions where added. Reading sublimes [docs](http://sublimetext.info/docs/en/extensibility/snippets.html) it seems that if a description isn't present, the name will be used in the snippet menu explaining the change.

**Comment by idleberg** [comment]
Hm, that sucks. I've never used snippets this way, I use them _as you type_, as shown in [this screenshot](https://github.com/idleberg/sublime-icon-fonts/blob/master/screenshot.gif). The reason I added descriptions is to give an idea, what the result will be. Some icon fonts use `<span>` or `<i>` tags, other use class names or data attributes.

**Example:**

![snippets](https://cloud.githubusercontent.com/assets/1504938/20604251/c39648ee-b265-11e6-976e-4db68d904311.png)

You can also see, that using snippets “my way” works the opposite, the description isn't the main selector but provides additional information.

I'm not sure what to do about this. Actually I've been thinking about going back to use `.sublime-completions`, since it's a more maintainable format.
